"""empty message

Revision ID: 55ef5139faf8
Revises: 8fb42713c45f
Create Date: 2020-12-08 18:05:49.037919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55ef5139faf8'
down_revision = '8fb42713c45f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
