"""empty message

Revision ID: 64862f17a4c3
Revises: fa6dbcba11cc
Create Date: 2020-12-08 16:19:59.621530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64862f17a4c3'
down_revision = 'fa6dbcba11cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
