"""empty message

Revision ID: 8fb42713c45f
Revises: 64862f17a4c3
Create Date: 2020-12-08 17:04:25.979727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fb42713c45f'
down_revision = '64862f17a4c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('test_id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('test_id')
    )
    # ### end Alembic commands ###
