"""empty message

Revision ID: d05c3e802fd1
Revises: 55ef5139faf8
Create Date: 2020-12-08 23:18:37.473527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd05c3e802fd1'
down_revision = '55ef5139faf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
